-- MySQL Script generated by MySQL Workbench
-- Fri Nov 15 20:46:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema d11FKghJiy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema d11FKghJiy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `d11FKghJiy` DEFAULT CHARACTER SET utf8 ;
USE `d11FKghJiy` ;

-- -----------------------------------------------------
-- Table `d11FKghJiy`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d11FKghJiy`.`clientes` ;

CREATE TABLE IF NOT EXISTS `d11FKghJiy`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `isAtivo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cpf_UNIQUE` ON `d11FKghJiy`.`clientes` (`cpf` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `d11FKghJiy`.`lojas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d11FKghJiy`.`lojas` ;

CREATE TABLE IF NOT EXISTS `d11FKghJiy`.`lojas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `isAtivo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d11FKghJiy`.`pets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d11FKghJiy`.`pets` ;

CREATE TABLE IF NOT EXISTS `d11FKghJiy`.`pets` (
  `id` INT NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  `idCliente` INT NOT NULL,
  `especie` VARCHAR(20) NOT NULL,
  `isAtivo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pets_idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `d11FKghJiy`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idCliente_UNIQUE` ON `d11FKghJiy`.`pets` (`idCliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `d11FKghJiy`.`lojas_clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d11FKghJiy`.`lojas_clientes` ;

CREATE TABLE IF NOT EXISTS `d11FKghJiy`.`lojas_clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idLoja` INT NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`id`, `idLoja`, `idCliente`),
  CONSTRAINT `fk_lojas_clientes_idLoja`
    FOREIGN KEY (`idLoja`)
    REFERENCES `d11FKghJiy`.`lojas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lojas_clientes_idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `d11FKghJiy`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_lojas_clientes_idLoja_idx` ON `d11FKghJiy`.`lojas_clientes` (`idLoja` ASC) VISIBLE;

CREATE INDEX `fk_lojas_clientes_idCliente_idx` ON `d11FKghJiy`.`lojas_clientes` (`idCliente` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
